#ifndef MINI_OS_EXCEPTION_OFFSETS_H
#define MINI_OS_EXCEPTION_OFFSETS_H
// Shared with preprocessed assembly; all offsets are bytes.
#define MINI_OS_FRAME_ENTRY_SP 248
#define MINI_OS_FRAME_SP_EL0 256
#define MINI_OS_FRAME_ESR 264
#define MINI_OS_FRAME_ELR 272
#define MINI_OS_FRAME_SPSR 280
#define MINI_OS_FRAME_FAR 288
#define MINI_OS_FRAME_VECTOR 296
#define MINI_OS_FRAME_SIZE 304
#define MINI_OS_CONTEXT_ACTIVE 0
#define MINI_OS_CONTEXT_X1 8
#define MINI_OS_CONTEXT_SP 16
#define MINI_OS_CONTEXT_VECTOR 24
#define MINI_OS_CONTEXT_STACK 32
#endif
